application: research-engine
version: 1-3-3
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: mail.app
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google(.+).html
  static_files: static/google\1.html
  upload: static/google(.+).html

- url: /css
  static_dir: css
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /cron/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
